### ISSUE TITLE
Open in JOSM not working for bounding box

### ISSUE THREAD

**Issue by srividyacb** [mapbox/osm-sidewalker#9]
@tcql 

The map seems to be updated with the new data. Today while working on this we came across a issue where `Open in JOSM` pop-up was not appearing with respect to bounding box for downloading multiple footways. 
It works fine when clicked on a single footway. 

![sidewalk11](https://cloud.githubusercontent.com/assets/3423533/11419221/e9badb18-944b-11e5-8363-88bf2254a177.gif)

We were working on this till yesterday and it was showing the pop-up to download in JOSM when clicked in vacant area. 

![](https://cloud.githubusercontent.com/assets/353700/10778887/3af4b908-7d50-11e5-9726-fbdbb62f539c.gif)

Also [JOSM link breaks](https://github.com/mapbox/mapping/issues/126#issuecomment-152431804) when we accidentally rotate the map.
> OSM-sidewalker map bug - Download in JOSM pop-up does not appear when the map is rotated (not north-up).

cc @planemad @maning

**Comment by batpad** [comment]
I did a little digging on this:

 Essentially, in this line: https://github.com/mapbox/osm-sidewalker/blob/mb-pages/index.src.js#L111 the callback passed to .featuresIn never gets called.

If you swap out the style to the older mapbox style id, and change the layer name to `old-sidewalks-world` then this works again. My guess is that this is something weird going on with the new `mbtile` or GL style?

Also, @tcql do you think this needs to be an issue in Mapbox GL JS? I guess even if there is something wrong with the layer, the callback should always be called, either with an error or a list of features?

**Comment by tcql** [comment]
This is a combo of two things. Mapbox studio seems to retain sources even if they are hidden or removed from a style. Gl-js `featuresIn` seems to fail when a source exists but doesn't have a visible layer. 

Once I can put together a good example of this, I'll ticket both projects. I fixed by adding beck the old sidewalks layer in my studio style and moving it behind the background, do that out exists but can't be seen visually
